become: yes
  tasks:
    - name: update apt packages 
      apt:
        force_apt_get: true
        upgrade: dist
        update_cache: yes
      become: true

    - name: Install nginx on webserver-1 
      apt: 
        name: nginx
        state: latest

- name: web2# Уникальное имя
  hosts: webserver-2.ru-central1.internal
  become: yes
  tasks:
    - name: update apt packages 
      apt:
        force_apt_get: true
        upgrade: dist
        update_cache: yes
      become: true

    - name: Install nginx on webserver-2 #
      apt: 
        name: nginx
        state: latest

- name: copy index.html webserver-1 
  hosts: webserver-1.ru-central1.internal
  become: yes
  tasks:
    - name: copy index_new.html
      ansible.builtin.copy:
        src: ./www/index1.html
        dest: /var/www/html/index.html
        owner: root
        group: sudo
        mode: "0644"

- name: copy index.html webserver-2 
  hosts: webserver-2.ru-central1.internal
  become: yes
  tasks:
    - name: copy index_new.html
      ansible.builtin.copy:
        src: ./www/index2.html
        dest: /var/www/html/index.html
        owner: root
        group: sudo
        mode: "0644"
